# Site settings
name: "Data Dilemmas and Discussions"
email: "lucystorts@gmail.com"
url: "https://lucystorts.github.io"
description: "Data Science Blog"
author: "Lucy Storts"
title: "Data Dilemmas and Discussions"
permalink: pretty
baseurl: /statsblog

# social
github:
  username: lucystorts

tableau:
  username: lucy.storts