# Site settings
name: "Data Dilemmas and Discussions"
email: "lucystorts@gmail.com"
url: "https://lucystorts.github.io"
description: "This blog will explore my different interests in data science and catalog my projects. Thanks for stopping by!"
author: "Lucy Storts"
title: "Data Dilemmas and Discussions"
permalink: pretty
baseurl: /statsblog

# social
github:
  username: lucystorts

#twitter:
#  username: username